### ISSUE TITLE
Stream is Unstable

### ISSUE THREAD

**Issue by noahajac** [tgorgdotcom/locast2plex#107]
Hello. I'm experiencing an issue with this script where the stream seems to be unstable. I'll play a channel and playback will start normally for a few seconds, get stuck for about 5, then keep playing. Afterwards it plays fine except for at seemingly random intervals where Plex will just start showing a loading symbol for about 20 seconds. Once it reloads it'll start to play where it left (I'm assuming this was already buffered by Plex before the stream was cut) but then jumps back to the stream.

I'm running this on CentOS 8 as a standard CLI script on a container on my Proxmox server. I've tried numerous different versions including the latest code from master. All of them have this issue. I've also tried using VLC instead of ffmpeg as outlined in #23 however that makes no change. Playing the m3u8 URL in a standard VLC window doesn't seem to have this issue.

I'm thinking this is something to do with the connection to Locast. In the logs I see `Error when getting the video URL: [Errno -2] Name or service not known` when the stream fails. What I suspect is happening is it loses connection for some reason and has to reconnect, halting the video output. Additionally, on rare occasions while testing I'd get this error 2 while l2p was attempting to startup and login. I don't see anything in my network that could be causing an issue. As mentioned before just trying on my desktop with VLC has no issues and pinging the Locast domain has no dropped pockets. I also see nothing in my firewall logs.

Below is the output given by l2c. Thank you for all the work you have done on this!

<details>
<summary>Output</summary>

```
[root@plex locast2plex-0.5.3]# python2 ./main.py 
Locast2Plex v0.5.3
Tuner count set to 3
UUID set to: uqmhqxkh...
Logging into Locast using username <REDACTED>...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 2020-12-06 09:51:06
Getting user location...
Getting location via IP Address.
Got external IP <REDACTED>.
Got location as New York - DMA 501 - Lat\Lon <REDACTED>
Getting list of stations based on DMA...
Loading FCC Stations list...
Starting device server on 127.0.0.1:6077
Starting SSDP server...
Locast2Plex is active and listening...
127.0.0.1 - - [09/Oct/2020 00:47:37] "GET /lineup.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:47:37] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:47:37] "GET /lineup_status.json HTTP/1.0" 200 -
Getting station info for 1574529688175...
Determining best video stream for 1574529688175...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
127.0.0.1 - - [09/Oct/2020 00:47:38] "GET /watch/1574529688175 HTTP/1.1" 200 -
ffmpeg version 4.2.4 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsrt --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[hls @ 0x5573baddfe40] Skip ('#EXT-X-VERSION:4')
[hls @ 0x5573baddfe40] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221892.ts' for reading
[hls @ 0x5573baddfe40] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221893.ts' for reading
127.0.0.1 - - [09/Oct/2020 00:47:40] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:47:40] "GET /lineup_status.json HTTP/1.0" 200 -
Input #0, hls, from 'https://hls.locastnet.org/proxy/nyc/variant/3lILBr7ncentAgciJ1I8YQqRFMiW8DBhZLi2voS1vW5DqAAdVwsuPx9TjbQ4AeBLqvkOTxjhZrM5JzkLocR94DJZyJdJyKGubyx863b6it92.m3u8':
  Duration: N/A, start: 74947.700978, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 854x480 [SAR 32880:32879 DAR 137:77], Closed Captions, 30 fps, 30 tbr, 90k tbn, 60 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mpegts, to 'pipe:1':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 854x480 [SAR 32880:32879 DAR 137:77], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[https @ 0x5573baf9ce80] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221894.ts' for reading
127.0.0.1 - - [09/Oct/2020 00:47:43] "GET /discover.json HTTP/1.0" 200 -.6kbits/s speed=10.1x    
127.0.0.1 - - [09/Oct/2020 00:47:43] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:47:46] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:47:46] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:47:49] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:47:49] "GET /lineup_status.json HTTP/1.0" 200 -
[hls @ 0x5573baddfe40] Skip ('#EXT-X-VERSION:4')
[https @ 0x5573baf9ce80] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221895.ts' for reading
127.0.0.1 - - [09/Oct/2020 00:47:52] "GET /discover.json HTTP/1.0" 200 -.9kbits/s speed=3.79x    
127.0.0.1 - - [09/Oct/2020 00:47:52] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:47:55] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:47:55] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:47:58] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:47:58] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x5573bae77dc0] Opening 'https://hls.locastnet.org/proxy/nyc/variant/3lILBr7ncentAgciJ1I8YQqRFMiW8DBhZLi2voS1vW5DqAAdVwsuPx9TjbQ4AeBLqvkOTxjhZrM5JzkLocR94DJZyJdJyKGubyx863b6it92.m3u8' for reading
[hls @ 0x5573baddfe40] Skip ('#EXT-X-VERSION:4')
[https @ 0x5573baf9ce80] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221896.ts' for reading
127.0.0.1 - - [09/Oct/2020 00:48:01] "GET /discover.json HTTP/1.0" 200 -.5kbits/s speed=2.01x    
127.0.0.1 - - [09/Oct/2020 00:48:01] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:48:04] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:48:04] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:48:07] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:48:07] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x5573bae77dc0] Opening 'https://hls.locastnet.org/proxy/nyc/variant/3lILBr7ncentAgciJ1I8YQqRFMiW8DBhZLi2voS1vW5DqAAdVwsuPx9TjbQ4AeBLqvkOTxjhZrM5JzkLocR94DJZyJdJyKGubyx863b6it92.m3u8' for reading
[hls @ 0x5573baddfe40] Skip ('#EXT-X-VERSION:4')
[https @ 0x5573baf9ce80] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221897.ts' for reading
127.0.0.1 - - [09/Oct/2020 00:48:10] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:48:10] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:48:13] "GET /discover.json HTTP/1.0" 200 -.7kbits/s speed=1.72x    
127.0.0.1 - - [09/Oct/2020 00:48:13] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:48:16] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:48:16] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:48:19] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:48:19] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x5573bae77dc0] Opening 'https://hls.locastnet.org/proxy/nyc/variant/3lILBr7ncentAgciJ1I8YQqRFMiW8DBhZLi2voS1vW5DqAAdVwsuPx9TjbQ4AeBLqvkOTxjhZrM5JzkLocR94DJZyJdJyKGubyx863b6it92.m3u8' for reading
Getting station info for 1574529688175...
Error when getting the video URL: [Errno -2] Name or service not known
127.0.0.1 - - [09/Oct/2020 00:49:01] "GET /watch/1574529688175 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50800)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./main.py", line 127, in do_GET
    ffmpeg_proc = subprocess.Popen(["ffmpeg", "-i", channelUri, "-codec", "copy", "-f", "mpegts", "pipe:1"], stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
----------------------------------------
Getting station info for 1574529688175...
Determining best video stream for 1574529688175...
127.0.0.1 - - [09/Oct/2020 00:49:02] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:02] "GET /lineup_status.json HTTP/1.0" 200 -
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
127.0.0.1 - - [09/Oct/2020 00:49:03] "GET /watch/1574529688175 HTTP/1.1" 200 -
ffmpeg version 4.2.4 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsrt --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[hls @ 0x5592efdbbe40] Skip ('#EXT-X-VERSION:4')
[hls @ 0x5592efdbbe40] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221900.ts' for reading
[hls @ 0x5592efdbbe40] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221901.ts' for reading
[tls @ 0x5573bad99500] Error in the pull function.
[hls @ 0x5573baddfe40] keepalive request failed for 'https://hls.locastnet.org/proxy/nyc/variant/3lILBr7ncentAgciJ1I8YQqRFMiW8DBhZLi2voS1vW5DqAAdVwsuPx9TjbQ4AeBLqvkOTxjhZrM5JzkLocR94DJZyJdJyKGubyx863b6it92.m3u8' when parsing playlist, retrying with new connection: Input/output error
Input #0, hls, from 'https://hls.locastnet.org/proxy/nyc/variant/61vGNCKKkX17vZTls3irRPDR1RrVvxOVUtDuzI9WmrwUDPFwP4LHC2ufoVipvtbSqwJnygxZ5WDWhqkC22pQANolkW8XX9STW3iyF48xzBVs.m3u8':
  Duration: N/A, start: 75027.700978, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 854x480 [SAR 32880:32879 DAR 137:77], Closed Captions, 30 fps, 30 tbr, 90k tbn, 60 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mpegts, to 'pipe:1':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 854x480 [SAR 32880:32879 DAR 137:77], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
127.0.0.1 - - [09/Oct/2020 00:49:05] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:05] "GET /lineup_status.json HTTP/1.0" 200 -
[hls @ 0x5573baddfe40] Skip ('#EXT-X-VERSION:4')
[https @ 0x5573baf9ce80] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221898.ts' for reading
[https @ 0x5573bb1affc0] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221899.ts' for reading
[https @ 0x5592f023ae00] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221902.ts' for reading
frame= 1871 fps= 22 q=-1.0 Lsize=    7934kB time=00:01:02.33 bitrate=1042.7kbits/s speed=0.729x    
video:5647kB audio:1462kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 11.606627%
Exiting normally, received signal 15.
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50356)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib64/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib64/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [09/Oct/2020 00:49:08] "GET /discover.json HTTP/1.0" 200 -.5kbits/s speed=11.9x    
127.0.0.1 - - [09/Oct/2020 00:49:08] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:11] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:11] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:14] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:14] "GET /lineup_status.json HTTP/1.0" 200 -
[hls @ 0x5592efdbbe40] Skip ('#EXT-X-VERSION:4')
[https @ 0x5592f023ae00] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221903.ts' for reading
127.0.0.1 - - [09/Oct/2020 00:49:17] "GET /discover.json HTTP/1.0" 200 -.5kbits/s speed=3.12x    
127.0.0.1 - - [09/Oct/2020 00:49:17] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:20] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:20] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:23] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:23] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x5592efe53dc0] Opening 'https://hls.locastnet.org/proxy/nyc/variant/61vGNCKKkX17vZTls3irRPDR1RrVvxOVUtDuzI9WmrwUDPFwP4LHC2ufoVipvtbSqwJnygxZ5WDWhqkC22pQANolkW8XX9STW3iyF48xzBVs.m3u8' for reading
[hls @ 0x5592efdbbe40] Skip ('#EXT-X-VERSION:4')
[https @ 0x5592f023ae00] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221904.ts' for reading
127.0.0.1 - - [09/Oct/2020 00:49:26] "GET /discover.json HTTP/1.0" 200 -.9kbits/s speed=2.41x    
127.0.0.1 - - [09/Oct/2020 00:49:26] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:29] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:29] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:33] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Oct/2020 00:49:33] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x5592efe53dc0] Opening 'https://hls.locastnet.org/proxy/nyc/variant/61vGNCKKkX17vZTls3irRPDR1RrVvxOVUtDuzI9WmrwUDPFwP4LHC2ufoVipvtbSqwJnygxZ5WDWhqkC22pQANolkW8XX9STW3iyF48xzBVs.m3u8' for reading
[hls @ 0x5592efdbbe40] Skip ('#EXT-X-VERSION:4')
[https @ 0x5592f023ae00] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221905.ts' for reading
127.0.0.1 - - [09/Oct/2020 00:49:36] "GET /discover.json HTTP/1.0" 200 -.1kbits/s speed=1.64x    
127.0.0.1 - - [09/Oct/2020 00:49:36] "GET /lineup_status.json HTTP/1.0" 200 -
^C^C received, shutting down the server0kB time=00:00:56.34 bitrate=1153.0kbits/s speed=1.82x    
[root@plex locast2plex-0.5.3]# [https @ 0x5592efe53dc0] Opening 'https://hls.locastnet.org/proxy/nyc/variant/61vGNCKKkX17vZTls3irRPDR1RrVvxOVUtDuzI9WmrwUDPFwP4LHC2ufoVipvtbSqwJnygxZ5WDWhqkC22pQANolkW8XX9STW3iyF48xzBVs.m3u8' for reading
[hls @ 0x5592efdbbe40] Skip ('#EXT-X-VERSION:4')
[https @ 0x5592f023ae00] Opening 'https://hls.locastnet.org/proxy/nyc/wcbsdabl160221906.ts' for reading
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:1: Broken pipe
frame= 1799 fps= 44 q=-1.0 Lsize=    8449kB time=00:00:59.96 bitrate=1154.2kbits/s speed=1.48x    
video:6185kB audio:1406kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 11.315524%
Exiting normally, received signal 2.

```
</details>

**Comment by noahajac** [comment]
Turns out it was a network issue! Sorry that I didn't realize earlier. Thanks for your hard work!
