### ISSUE TITLE
Unable to stream to remote Plex server

### ISSUE THREAD

**Issue by wkdbuzz** [tgorgdotcom/locast2plex#111]
Hi,

I have locast2plex installed on a small linux server in a locast area.  i'd like to stream locast through my plex server which is on a separate network.  

The server starts successfully and Plex is able to connect and do its thing but none of the channels will play back giving this error:   Could not tune channel. Please check your tuner or antenna.

Plex logs show:  
[Transcoder] http://192.168.1.10:36077/watch/1594934032780: Connection timed out

The IP is the internal of the server hosting L2P.   Is there a way to make that connect to my external IP?

On the locast2plex server, the logs see the connection coming in:   (external IPs redacted)
192.131.x.x - - [18/Oct/2020 17:35:28] "GET /lineup_status.json HTTP/1.0" 200 -
192.131.x.x - - [18/Oct/2020 17:35:30] "GET /discover.json HTTP/1.0" 200 -
192.131.x.x - - [18/Oct/2020 17:35:30] "GET /lineup_status.json HTTP/1.0" 200 -

No other errors or obvious problems.  Let me know if there's anything else i can share.

**Comment by SmithLMichael** [comment]
Have you set up remote access in your Plex server? [Remote Access](https://support.plex.tv/articles/200289506-remote-access/)

**Comment by wkdbuzz** [comment]
Hi,

Yes, streaming Plex remotely is how i watch exclusively.  My setup is running on a seedbox and i can't (or so it appears) to run the locast2plex service locally.  

What I hoped to do is have Plex connect to my linux box at home running locast2plex and within the locast region.

In Plex, i'm able to add the device by using the IP and Port of my linux box at home.   It connects, finds all the channels, does all that magic but when it tries to play, it fails.   The log says it can't connect and the IP is to the internal IP in my house.  I believe this can be fixed if there was a way to tell it to use the external IP instead.  The port is connect.

`[Transcoder] http://192.168.1.10:36077/watch/1594934032780: Connection timed out
`

Hope that clears things up!

PS-  The error I get when trying to L2P on the same server running Plex,  this is what I get:
```

python3 ./main.py 
Locast2Plex v0.5.3
Tuner count set to 3
UUID set to: xx...
Logging into Locast using username xx@xx.com...
Traceback (most recent call last):
  File "/xx/xx/xx/apps/locast2plex-master/LocastService.py", line 19, in wrapper_func
    return f(self, *args, **kwargs)
  File "/xx/xx/xx/apps/locast2plex-master/LocastService.py", line 73, in login
    loginRes = json.load(loginOpn)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 394, in <module>
    if (not locast.login(LOCAST_USERNAME, LOCAST_PASSWORD)) or (not locast.validate_user()):
  File "/xx/xx/xx/apps/locast2plex-master/LocastService.py", line 27, in wrapper_func
    print("Error in function {}: {}".format(f.__name__, e.message or e.reason))
AttributeError: 'JSONDecodeError' object has no attribute 'message'

```

**Comment by jcastilloalonso** [comment]
What's your config.ini setting for plex_accessible_ip? Try setting that for your external IP address.

**Comment by wkdbuzz** [comment]
> What's your config.ini setting for plex_accessible_ip? Try setting that for your external IP address.

It's the IP of the server.  When I try to use my external IP, I get the below error and will not start:

```
Starting device server on 75.24.x.x:36077
Traceback (most recent call last):
  File "main.py", line 404, in <module>
    serverSocket.bind((LISTEN_ADDY, int(LISTEN_PORT)))
OSError: [Errno 99] Cannot assign requested address
```

**Comment by jcastilloalonso** [comment]
Seems more than a issue this is more of an enhancement then

**Comment by Fyb3roptik** [comment]
I had the same issue and used my internal ip (192.168.1.x) and that fixed it
