### ISSUE TITLE
Set up seemed fine, now wont start

### ISSUE THREAD

**Issue by benplace** [tgorgdotcom/locast2plex#120]
I did docker-compose up and things seemed to go fine, when doing run command I got an error decided to start over, deleted folder re-unzipped it, now no matter what I do I get:
Locast2Plex v0.5.3

Tuner count set to 3

No UUID found. Generating one now...

Traceback (most recent call last):

File "/app/main.py", line 368, in <module>

config_handler.set('main', 'uuid', DEVICE_UUID)

File "/usr/lib/python3.8/configparser.py", line 902, in set

raise NoSectionError(section) from None

configparser.NoSectionError: No section: 'main'

It repeats this 3 times and then stops trying to start.
Any ideas?

**Comment by crash1015** [comment]
Same issue here.

**Comment by deathbybandaid** [comment]
Did you copy the config example file?

**Comment by benplace** [comment]
Yes I copied that to config.ini and made appropriate changes

**Comment by benplace** [comment]
My config:
[main]
locast_username=xxxxxxxx@gmail.com
locast_password=xxxxxx
plex_accessible_ip=192.168.86.223

#plex_accessible_port=6077
#bytes_per_read=1152000
#tuner_count=3
#uuid=
#reporting_model=HDHR3-US
#reporting_firmware_name=hdhomerun3_atsc
#reporting_firmware_ver=20150826
#concurrent_listeners=10

**Comment by chamby90** [comment]
I just opened a new issue for this as well... didnt see this ticket was already created.

I am having this same issue, and found in a closed ticket that this might of solved the issue:
"You have to mount the file instead of the folder. For instance:

/mnt/cache/appdata/locast2plex/config.ini 
Container path: /app/config.ini"

Can anybody point me in the direction of how to do that in docker?

**Comment by tgorgdotcom** [comment]
Hello @benplace.  Where did you place the config file?  Does it match what is in the docker-compose.yml file?

**Comment by RocketSLC** [comment]
I'm also having this issue on an Unraid docker. Not sure when it started, but noticed that I couldn't launch locast2plex for the same error above.

**Comment by RocketSLC** [comment]
I seemed to have been able my issue by manually linking to a config file with -v.
