### ISSUE TITLE
Server starts and runs, but when I try to connect from Plex I get an error

### ISSUE THREAD

**Issue by benplace** [tgorgdotcom/locast2plex#125]
Can anyone help with this error?
C:\LoCast\locast2plex-old-merge>python main.py
Locast2Plex v0.5.2
Tuner count set to 3
UUID set to: ypjuqhkj...
Logging into Locast using username xxxxxx@gmail.com...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1609081044.0
Getting user location...
User location obtained as xx.xxxx/-xx.xxxx
Getting user's media market (DMA)...
DMA found as 602: Chicago
Getting list of stations based on DMA...
Loading FCC Stations list...
Starting device server on 192.168.1.250:6077
Starting SSDP server...
Locast2Plex is active and listening...
'I TRY TO CONNECT HERE:'
192.168.1.250 - - [29/Oct/2020 13:48:57] "GET /discover.json HTTP/1.0" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.250', 36303)
Traceback (most recent call last):
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 414, in handle_one_request
    method()
  File "main.py", line 63, in do_GET
    base_url))
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------

**Comment by sean-parent** [comment]
I'm hitting something similar:
```
Locast2Plex is active and listening...
127.0.0.1 - - [06/Nov/2020 20:15:04] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [06/Nov/2020 20:15:04] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [06/Nov/2020 20:15:04] "GET /lineup.json HTTP/1.0" 200 -
Getting station info for 1283...
Determining best video stream for 1283...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
127.0.0.1 - - [06/Nov/2020 20:15:05] "GET /watch/1283 HTTP/1.1" 200 -
ffmpeg version git-2020-01-21-fc6fde2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 38.100 / 56. 38.100
  libavcodec     58. 66.100 / 58. 66.100
  libavformat    58. 35.104 / 58. 35.104
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 71.100 /  7. 71.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[hls @ 0000017923418e40] Skip ('#EXT-X-VERSION:4')
[hls @ 0000017923418e40] Opening 'https://sfo.locastnet.org/proxy/sfo/ktvubuzzr160472264.ts' for reading
[hls @ 0000017923418e40] Opening 'https://sfo.locastnet.org/proxy/sfo/ktvubuzzr160472265.ts' for reading
Input #0, hls, from 'https://sfo.locastnet.org/proxy/sfo/variant/4yhK0QNicjAAbP990zjYEEJmoCnmr0zqB8UWweIgTtLCdAOQzNeXBtgNJ1OYYMiNJqCXccct0pr6XMoSZwarQrPrakRfmwqVWi09mK7gRvC1.m3u8':
  Duration: N/A, start: 23113.967289, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 854x480 [SAR 32880:32879 DAR 137:77], Closed Captions, 30 fps, 30 tbr, 90k tbn, 60 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mpegts, to 'pipe:1':
  Metadata:
    encoder         : Lavf58.35.104
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 854x480 [SAR 32880:32879 DAR 137:77], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[https @ 0000017923b7e040] Opening 'https://sfo.locastnet.org/proxy/sfo/ktvubuzzr160472266.ts' for reading
127.0.0.1 - - [06/Nov/2020 20:15:06] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [06/Nov/2020 20:15:06] "GET /lineup_status.json HTTP/1.0" 200 -
[hls @ 0000017923418e40] Skip ('#EXT-X-VERSION:4')
[https @ 0000017923b7e040] Opening 'https://sfo.locastnet.org/proxy/sfo/ktvubuzzr160472267.ts' for reading
[https @ 0000017923f152c0] Opening 'https://sfo.locastnet.org/proxy/sfo/variant/4yhK0QNicjAAbP990zjYEEJmoCnmr0zqB8UWweIgTtLCdAOQzNeXBtgNJ1OYYMiNJqCXccct0pr6XMoSZwarQrPrakRfmwqVWi09mK7gRvC1.m3u8' for reading
[hls @ 0000017923418e40] Skip ('#EXT-X-VERSION:4')
[https @ 0000017923b7e040] Opening 'https://sfo.locastnet.org/proxy/sfo/ktvubuzzr160472268.ts' for reading
----------------------------------------kB time=00:00:39.97 bitrate= 683.5kbits/s speed=   2x
Exception happened during processing of request from ('127.0.0.1', 53416)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\http\server.py", line 415, in handle_one_request
    method()
  File "main.py", line 139, in do_GET
    self.wfile.write(videoData)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:1: Broken pipe
frame= 1206 fps= 60 q=-1.0 Lsize=    3376kB time=00:00:40.19 bitrate= 688.2kbits/s speed=2.01x
video:2047kB audio:942kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 12.945132%
Conversion failed!
```

**Comment by tgorgdotcom** [comment]
Hello @benplace  What version of python are you running?
