### ISSUE TITLE
Will not start

### ISSUE THREAD

**Issue by BartManX** [tgorgdotcom/locast2plex#13]
tried on

WINDOWS 10 : Python 2.7.17
the only thing that happened 
-------------------------------------
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import subprocess, os, sys, random, threading, socket, time, SocketServer
ModuleNotFoundError: No module named 'SocketServer'

----------------------------------------------------------------------------
then on UBUNTU 20.04 : Python 2.7.18rc1
Started out looking like it was going to work 
then

 Getting user's media market (DMA)...
DMA found as 678
Getting list of stations based on DMA...
Loading FCC Stations list...
Traceback (most recent call last):
  File "main.py", line 324, in <module>
    station_list = locast.get_stations()
  File "/home/abardt/locast2plex/LocastService.py", line 195, in get_stations
    fcc_market = dma_mapping[str(self.current_dma)]
KeyError: '678'

**Comment by tgorgdotcom** [comment]
Hello.  What city are you trying to receive stations from?  Looks like locast is reporting a city that it doesn't support yet.

**Comment by steventwheeler** [comment]
I am getting a similar error running via Docker, in Minneapolis (DMA 613). Locast appears to support my location as I can watch from their website without issue. Here are my logs with debugging enabled.

```
Locast2Plex v0.4.2
DEBUG MODE ACTIVE
UUID found.
UUID set to: lrtrvhsi...
Logging into Locast using username *********...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1600352633
Getting user location...
User location obtained as *******/*******
Getting user's media market (DMA)...
DMA found as 613
Getting list of stations based on DMA...
Loading FCC Stations list...
Traceback (most recent call last):
  File "/app/main.py", line 324, in <module>
    station_list = locast.get_stations()
  File "/app/LocastService.py", line 195, in get_stations
    fcc_market = dma_mapping[str(self.current_dma)]
KeyError: '613'
```

My gut feeling is that there's an issue with [tv_stations.json](https://github.com/tgorgdotcom/locast2plex/blob/master/tv_stations.json) as the Minneapolis/St. Paul area channels do not reference the string `'613'`. Or, perhaps something was supposed to translate `'613'` into `'MINNEAPOLIS-ST. PAUL'` which is the value under the `nielsen_dma` key.

**Comment by tgorgdotcom** [comment]
Excellent work @steventwheeler !  I'll bring it in.

@BartManX , I'll leave this issue open in case you need to reply back

**Comment by TyNavarre** [comment]
I am having the same issue as @BartManX when attempting to run via Windows CLI. Is there a way to address it?

**Comment by BartManX** [comment]
> Excellent work @steventwheeler ! I'll bring it in.
> 
> @BartManX , I'll leave this issue open in case you need to reply back

i am in the Houston Texas location

**Comment by tgorgdotcom** [comment]
@BartManX -- Ah, okay.  It looks like it looks the GeoIP is detecting a different location than Houston.  We did change the way we did GeoIP in 0.5.3 -- please try that first (note there's some new steps you'll need to take to get it working, see readme).  There's some other things we can try as well, but we would probably need locast2plex upgraded anyways to start.

**Comment by deathbybandaid** [comment]
#92 helps mittigate some of the keyerror issues, mock_location helps with this as well.

The original issue may go away once we've switched to py3
