### ISSUE TITLE
Tested latest Code

### ISSUE THREAD

**Issue by libersongm** [tgorgdotcom/locast2plex#137]
Tested latest code running from Dallas-Fort Worth.  Run as a script at start up and get the following error:   Older code from previous fix still works.   Noticed listed station is Fort Worth not Dallas-Fort Worth for #623.   Thanks in advance.

Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gary/Downloads/locast2plex-master/main.py", line 67, in <module>
    stations.refresh_dma_stations_and_channels(config, locast, location_info.location)
  File "/home/gary/Downloads/locast2plex-master/lib/stations.py", line 38, in refresh_dma_stations_and_channels
    fcc_stations = get_fcc_stations(config)
  File "/home/gary/Downloads/locast2plex-master/lib/stations.py", line 144, in get_fcc_stations
    online_file_time = get_online_file_time(facility_url)
  File "/home/gary/Downloads/locast2plex-master/lib/stations.py", line 44, in get_online_file_time
    resp = urllib.request.urlopen(url_head)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)>

**Comment by deathbybandaid** [comment]
@tgorgdotcom This is what I had encountered in my testing forever ago...

https://github.com/tgorgdotcom/locast2plex/pull/92#issuecomment-696918548

The domain that hosts the fcc database doesn't have a proper SSL cert

**Comment by tgorgdotcom** [comment]
Ah, gotcha.  I just pushed an update (0.6.1), let me know if that works.

Thanks again @deathbybandaid!

**Comment by libersongm** [comment]
Copy recording parade for wife as soon as done will check.   Thanks for the quick response.

**Comment by libersongm** [comment]
Ok tested out.  Initially had an issue with tuner error.   Deleted and reset the DVR still issues.   Determine had two instances running, killed all tested reset DVR, seems to be work fine.   Thank you for the quick response.   Have a great thanksgiving.

**Comment by tgorgdotcom** [comment]
No problem.
