### ISSUE TITLE
Update fails if password contains % character

### ISSUE THREAD

**Issue by burntoc** [tgorgdotcom/locast2plex#142]
I updated my Unraid Docker and then it wouldn't start again.  Based on this line in the log, I realized it was probably failing because my password had a % character in it.  I changed it to remove that, updated the config.ini and it works now.

`Initiating Locast2Plex v0.6.1
Opening and Verifying Configuration File.
/app/config/config.ini
Loading Configuration File: /app/config/config.ini
Traceback (most recent call last):
File "/app/main.py", line 49, in <module>
....<snip>....
File "/usr/local/lib/python3.8/configparser.py", line 442, in _interpolate_some
raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%restofpassword
`

**Comment by teconmoon** [comment]
Seconded, my password had a % at the end of it and fails to load.

**Comment by tgorgdotcom** [comment]
Hello all.  Just updated l2p with a fix (0.6.2).  Let me know if that corrects your issues.  Thanks!
