### ISSUE TITLE
Error in function get_ip_location: [Errno -3] 

### ISSUE THREAD

**Issue by kingstonwa** [tgorgdotcom/locast2plex#197]
Just tried to install the new version via SSH and got the following error, please help

[~] # docker run -v /share/CACHEDEV1_DATA/homes/bob/config.ini:/app/config/config.ini -p 6077:6077 tgorg/locast2plex
Initiating Locast2Plex v0.6.2
Opening and Verifying Configuration File.
/app/config/config.ini
Loading Configuration File: /app/config/config.ini
Tuner count set to 3
Server is set to run on  127.0.0.1:6077
UUID set to: lmxjmviw...
Getting user location...
Getting location via IP Address.
**Error in function get_ip_location: [Errno -3] Try again
Could not acertain location.  Exiting...**

**Comment by kingstonwa** [comment]
Well I restarted my Qnap and that error went away, now I get 

[/share/CACHEDEV1_DATA/homes/locast2plex] # docker run -v /share/CACHEDEV1_DATA/homes/locast2plex/config.ini:/app/config/config.ini -p 6077:6077 tgorg/locast2plex
Initiating Locast2Plex v0.6.2
Opening and Verifying Configuration File.
/app/config/config.ini
Loading Configuration File: /app/config/config.ini
Tuner count set to 3
Server is set to run on  127.0.0.1:6077
UUID set to: xxxxxx...
Getting user location...
Getting location via IP Address.
Got external IP xxxxxxxxxxxxx.
Got location as Seattle - DMA 819 - Lat\Lon 47.7557\-122.3415
Logging into Locast using username xxxxxxxxxxxxxxxxxxxx...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 2021-02-18 05:20:14
Starting First time Stations refresh...
Checking FCC facilities database for updates.
Traceback (most recent call last):
  File "/app/main.py", line 67, in <module>
    stations.refresh_dma_stations_and_channels(config, locast, location_info.location)
  File "/app/lib/stations.py", line 38, in refresh_dma_stations_and_channels
    fcc_stations = get_fcc_stations(config)
  File "/app/lib/stations.py", line 144, in get_fcc_stations
    online_file_time = get_online_file_time(facility_url)
  File "/app/lib/stations.py", line 44, in get_online_file_time
    resp = urllib.request.urlopen(url_head)
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1354, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
**ConnectionResetError: [Errno 104] Connection reset by peer**

**Comment by parasoft-sang** [comment]
To me, main branch execution fails and similar error:

ocast2plex@duckie:~$ python3.9 main.py
Initiating Locast2Plex v0.6.4
Opening and Verifying Configuration File.
/opt/locast2plex/config/config.ini
/opt/locast2plex/config.ini
Loading Configuration File: /opt/locast2plex/config.ini
Tuner count set to 4
Server is set to run on  127.0.0.1:6077
UUID set to: XXXXX...
Getting user location...
Getting location via IP Address.
Got external IP 208.82.99.146.
Got location as San Francisco - DMA 807 - Lat\Lon 37.3394\-121.895
Logging into Locast using username XXXXXXX...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 2022-08-17 08:26:17
Starting First time Stations refresh...
Checking FCC facilities database for updates.
Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/locast2plex/main.py", line 67, in <module>
    stations.refresh_dma_stations_and_channels(config, locast, location_info.location)
  File "/opt/locast2plex/lib/stations.py", line 38, in refresh_dma_stations_and_channels
    fcc_stations = get_fcc_stations(config)
  File "/opt/locast2plex/lib/stations.py", line 144, in get_fcc_stations
    online_file_time = get_online_file_time(facility_url)
  File "/opt/locast2plex/lib/stations.py", line 44, in get_online_file_time
    resp = urllib.request.urlopen(url_head)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1385, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1345, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1122)>


I tried with python 3.6, 3.8 (default), and 3.9 but all python errors are the same.
The host is Ubuntu 20.04.1 LTS

**Comment by tgorgdotcom** [comment]
@kingstonwa - The first error was just fixed with our v0.6.4 release.  Upgrading should fix that issue for docker users

@parasoft-sang - This is related issue that arose for some installations with v0.6.4  I have a fix for this with some good results from another user -- would you be able to test it out too?

Attached below is an updated version of `stations.py` (you'll need to unzip it first), located in the `/lib` folder in your locast2plex directory.  If you could check to see if this fixes it, I can push it out for the next release.  
[stations.zip](https://github.com/tgorgdotcom/locast2plex/files/5853324/stations.zip)

**Comment by daveman918** [comment]
Was having the same errors. The new stations.py fixed it. Back up and running. Thanks!

**Comment by libersongm** [comment]
Have similar error tonight, will check and report back.

Thanks,
Gary

**Comment by libersongm** [comment]
Well that seems to fix it.   Thanks keep you posted on any other issues.

Very Respectfully,
Gary

**Comment by parasoft-sang** [comment]
Hi,

It fixed the issue. Thank you

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kingstonwa** [comment]
Hi @tgorgdotcom please pardon my ignorance, but when using the docker run -v /share/CACHEDEV1_DATA/.... method on my Qnap to create the docker, where is the root folder for the locast2plex files that may need updating?

**Comment by gluesniffined** [comment]
The new stations.py fixed the issue for me as well.  Thank you so much!

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

**Comment by tgorgdotcom** [comment]
@kingstonwa - if you're using docker, just update the docker image associated with the image, rather than update files manually.

**Comment by tgorgdotcom** [comment]
Hello all.  I implemented the changes in stations.py to v0.6.5.  Let me know if anyone is running into any additional issues.

**Comment by shinycard255** [comment]
Tried getting locast2plex up and running and am running into this same issue... I'm also relatively new to docker 


Initiating Locast2Plex v0.6.5
Opening and Verifying Configuration File.
/app/config/config.ini
/app/config.ini
Loading Configuration File: /app/config.ini
Tuner count set to 3
Server is set to run on  127.0.0.1:6077
UUID set to: ulvpqnhq...
Getting user location...
Getting location via IP Address.
Error in function get_ip_location: [Errno -3] Try again
Could not acertain location.  Exiting...

**Comment by RXtreme8** [comment]
having same error condition: _Error in function get_ip_location: [Errno -3] Try again  Could not acertain location. Exiting_.

I tried using the zipcode, lat and log overrides but no change.
I suspect it's something with my docker not providing an IP to the container or proxying it or something... but i can't figure it out.

**Comment by wolffcatsky** [comment]
> having same error condition: _Error in function get_ip_location: [Errno -3] Try again Could not acertain location. Exiting_.
> 
> I tried using the zipcode, lat and log overrides but no change.
> I suspect it's something with my docker not providing an IP to the container or proxying it or something... but i can't figure it out.

I'm NOT using Docker and get the same error.

**Comment by RXtreme8** [comment]
My work around when using Docker was to use the 'Host' network instead of
'Bridge'.  I suspect something with the virtual network bridge uses was
causing the IP geolocation to fail when connecting to Locast Api.

**Comment by wolffcatsky** [comment]
Thanks.  I wasn’t using Docker,  it I’ll try it.

**Comment by shinycard255** [comment]
@RXtreme8 i will have to give this a try. thanks!

**Comment by shinycard255** [comment]
@RXtreme8 using 'Host' network fixed my issue. thank you

**Comment by rqbanerjee** [comment]
I also got it to work by using Host mode.
Here's my docker-compose.yml file. I 
1. added the network_mode line
2. removed the ports section 
```
version: '2'
services:
  locast2plex:
    network_mode: "host"
    image: tgorg/locast2plex
    container_name: locast2plex
    restart: unless-stopped
    environment:
      - username=email@yahoo.com
      - 'password=abcdefg
      - external_addy=192.168.1.999
      - external_port=6077
      - debug=yes
    volumes:
      - ./config.ini:/app/config/config.ini

```
