### ISSUE TITLE
Unable to load my complete channel lineup

### ISSUE THREAD

**Issue by arejay73** [tgorgdotcom/locast2plex#2]
When I run I am only able to get about half of my channels that are in my lineup.  I thought it might be related to too many connections so I tried to place a sleep timer in main.py in-between stream lookups, but still no luck.

For example, I know that channel 2.2 is part of my lineup, but when it loads it says no streams available.

**Comment by arejay73** [comment]
I get the Stream information for 46.1, but the other, 46.2 and 46.3 I don't.  But I can tune to those in my locust app.  Using postman I am seeing URLs like this,

`"streamUrl": "https://acdn.locastnet.org/msg/stream_limit.m3u8"` - Which leads me to believe somewhere the calculations of playlist is making me hit the stream limit.  I tried to slowdown the process to avoid this, but doesn't seem to have worked.

`locast2plex_1  | Getting station info for 46.1 CBS...
locast2plex_1  | Determining best video stream for 46.1 CBS...
locast2plex_1  | Found 3 Playlists
locast2plex_1  | 46.1 CBS will use 1280x720 resolution at 2700000bps
locast2plex_1  | Getting station info for 46.2 COZITV...
locast2plex_1  | Determining best video stream for 46.2 COZITV...
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for 46.3 GRIT...
locast2plex_1  | Determining best video stream for 46.3 GRIT...
locast2plex_1  | Found 0 Playlists
`

**Comment by tgorgdotcom** [comment]
Hello.  It's definitely due to how I'm getting the station list streams.  Because I'm using telly, I grab all of the station stream urls ahead of time and have to keep track of them every so often.  Every inquiry into a stream counts as a concurrent stream in Locast's API, and Locast limits how many there are.  

I am working on removing that dependency now and should only need the stream url when you are tuning into that channel.  Also, I have added correct station labeling.  Hoping to get it out shortly.

**Comment by tgorgdotcom** [comment]
Hello again.  Could you try pulling the latest version?  This will require a few changes to the environment variables, but the update should eliminate the stream limiting when polling for channels.

**Comment by arejay73** [comment]
What changes to environment variables are you referring?  I downloaded and updated yaml file and ran command: docker-compose up

And got the following:

```
locast2plex_1  | Getting list of stations based on DMA...
locast2plex_1  | Getting station info for WSBDT...
locast2plex_1  | Determining best video stream for WSBDT...
locast2plex_1  | Found 3 Playlists
locast2plex_1  | WSBDT will use 1280x720 resolution at 2700000bps
locast2plex_1  | Getting station info for WSBDT2...
locast2plex_1  | Determining best video stream for WSBDT2...
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for WSBDT3...
locast2plex_1  | Determining best video stream for WSBDT3...
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for WAGADT...
locast2plex_1  | Determining best video stream for WAGADT...
locast2plex_1  | Found 3 Playlists
locast2plex_1  | WAGADT will use 1280x720 resolution at 2700000bps
locast2plex_1  | Getting station info for WAGADT2...
locast2plex_1  | Determining best video stream for WAGADT2...
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for WAGADT3...
locast2plex_1  | Determining best video stream for WAGADT3...
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for WAGADT4...
locast2plex_1  | Determining best video stream for WAGADT4...
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for WAGADT5...
locast2plex_1  | Determining best video stream for WAGADT5...
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for WGTVDT...
locast2plex_1  | Determining best video stream for WGTVDT...
locast2plex_1  | Found 3 Playlists
locast2plex_1  | WGTVDT will use 1280x720 resolution at 2700000bps
locast2plex_1  | Getting station info for WGTVDT2...
locast2plex_1  | Determining best video stream for WGTVDT2...
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for WGTVDT3...
locast2plex_1  | Determining best video stream for WGTVDT3...Traceback (most recent call last):
locast2plex_1  |   File "/app/main.py", line 322, in <module>
locast2plex_1  |     if (not locast_login()) or (not validate_user()) or (not generate_m3u()):
locast2plex_1  |   File "/app/main.py", line 265, in generate_m3u
locast2plex_1  |     videoUrlM3u = m3u8.load(videoUrlRes['streamUrl'])
locast2plex_1  |   File "/app/m3u8/__init__.py", line 56, in load
locast2plex_1  |     return _load_from_uri(uri, timeout, headers, custom_tags_parser, verify_ssl)
locast2plex_1  |   File "/app/m3u8/__init__.py", line 68, in _load_from_uri
locast2plex_1  |     resource = urlopen(request, timeout=timeout, context=context)
locast2plex_1  |   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
locast2plex_1  | 
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for WGTVDT4...
locast2plex_1  | Determining best video stream for WGTVDT4...
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for WXIADT...
locast2plex_1  | Determining best video stream for WXIADT...
locast2plex_1  | Found 3 Playlists
locast2plex_1  | WXIADT will use 1280x720 resolution at 2700000bps
locast2plex_1  | Getting station info for WXIADT3...
locast2plex_1  | Determining best video stream for WXIADT3...
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for WXIADT4...
locast2plex_1  | Determining best video stream for WXIADT4...
locast2plex_1  | Found 0 Playlists
locast2plex_1  | No streams found for this station.  Skipping...
locast2plex_1  | Getting station info for WPXADT...
locast2plex_1  | Determining best video stream for WPXADT...
locast2plex_1  | Found 3 Playlists
locast2plex_1  | WPXADT will use 1280x720 resolution at 2700000bps
locast2plex_1  | Getting station info for WPXADT2...
locast2plex_1  | Determining best video stream for WPXADT2...
locast2plex_1  |     return opener.open(url, data, timeout)
locast2plex_1  |   File "/usr/lib/python2.7/urllib2.py", line 429, in open
locast2plex_1  |     response = self._open(req, data)
locast2plex_1  |   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
locast2plex_1  |     '_open', req)
locast2plex_1  |   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
locast2plex_1  |     result = func(*args)
locast2plex_1  |   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
locast2plex_1  |     context=self._context)
locast2plex_1  |   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
locast2plex_1  |     raise URLError(err)
locast2plex_1  | urllib2.URLError: <urlopen error [Errno -3] Try again>
```

**Comment by tgorgdotcom** [comment]
Hello.  I renamed listen_addy to external_addy and added the external_port variable.  As for the output,  it seems like the container is running on an older version of the image.  You may need to recreate the container for the updated image to be used.  Hope that helps!

**Comment by arejay73** [comment]
I have redownloaded the docker image and when I start I get this message.

```
docker-compose up
WARNING: The external_port variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
locast2plex.ports is invalid: Port ranges don't match in length
```

**Comment by tgorgdotcom** [comment]
Hello.  I just pushed an update that fixed using docker-compose.  I broke out the config to a docker-compose.env file, so you would modify that before running docker-compose up instead of modifying docker-compose.yml.  Let me know if that works.  Thanks!

**Comment by arejay73** [comment]
I have downloaded a new version.  Updated the docker-compose.env. and run the command docker-compose up.  I get the same error.  I had to change the name of the file from docker-compose.env to just ".env".  Then the docker-compose up command would work.

Then I received this Telly error:
```
locast2plex_1  | Running Telly.  Configured to run on IP 0.0.0.0...
locast2plex_1  | time="2020-06-09T18:31:59Z" level=info msg="telly is preparing to go live (version=1.1.0.6, branch=dev, revision=741108cd2100cf9f4d3a13f771d1ebe5132baae6)"
locast2plex_1  | Telly process failed.  Exiting...
```

Content of env file
```
username=XXX
password=XXX
external_addy=127.0.0.1
external_port=6077
debug=false
```
