### ISSUE TITLE
locast2plex-0.6.5 on Windows Docker: Remote end closed connection without response

### ISSUE THREAD

**Issue by wlfuer** [tgorgdotcom/locast2plex#205]
First of all thank you Thomas and everyone here that makes this work! I love this solution and it has been working great on my NAS Plex + locast2plex solution using this since about v0.5.3.  Since then I've gone along on the upgrades, etc. My last working build was v0.6.3.  It seemed to be working up until maybe 5 days ago, I don't watch TV often but noticed then that my recordings failed.

So then I check and sure enough a new version. I downloaded and went through the basic install and used my config like I have before. I got errors during the 'docker-compose up'... the container was created and it keep trying to start and crash.

I decided to revert, deleted new container, tried setup again... but now same error even on old version.  I don't know what else to add, I did recent do windows updates - maybe related but I'm pretty sure I was working after that at least for a while.

Here is my log when I try to setup. One note I see is the header shows like I'm setting up v0.6.2 ... I thought that maybe something was a remnant somewhere? 

Any ideas on this? I just watch locast.org stuff real-time lately if I want to watch anything so I'm not in a crisis or anything .. and I'm newly single otherwise this would have been a major issue. :O  

Thanks for any help or pointers what I might be doing wrong. I looked at some other threads and they weren't exactly this problem + I was using the build everyone seemed to be having good results with:

C:\locast2plex>docker-compose up
Creating locast2plex_locast2plex_1 ... done    Attaching to locast2plex_locast2plex_1
locast2plex_1  | Initiating Locast2Plex v0.6.2
locast2plex_1  | Opening and Verifying Configuration File.
locast2plex_1  | /app/config/config.ini
locast2plex_1  | Loading Configuration File: /app/config/config.ini
locast2plex_1  | Tuner count set to 3
locast2plex_1  | Server is set to run on  192.168.1.106:6077
locast2plex_1  | UUID set to: jrhqhjxo...
locast2plex_1  | Getting user location...
locast2plex_1  | Getting location via IP Address.
locast2plex_1  | Got external IP 71.*******.180.
locast2plex_1  | Got location as Seattle - DMA 819 - Lat\Lon 47.558098\-121.90371
locast2plex_1  | Logging into Locast using username w*********l.com...
locast2plex_1  | Validating User Info...
locast2plex_1  | User Info obtained.
locast2plex_1  | User didDonate: True
locast2plex_1  | User donationExpire: 2021-07-30 13:47:15
locast2plex_1  | Starting First time Stations refresh...
locast2plex_1  | Checking FCC facilities database for updates.
locast2plex_1  | Traceback (most recent call last):
locast2plex_1  |   File "/app/main.py", line 67, in <module>
locast2plex_1  |     stations.refresh_dma_stations_and_channels(config, locast, location_info.location)
locast2plex_1  |   File "/app/lib/stations.py", line 38, in refresh_dma_stations_and_channels
locast2plex_1  |     fcc_stations = get_fcc_stations(config)
locast2plex_1  |   File "/app/lib/stations.py", line 144, in get_fcc_stations
locast2plex_1  |     online_file_time = get_online_file_time(facility_url)
locast2plex_1  |   File "/app/lib/stations.py", line 44, in get_online_file_time
locast2plex_1  |     resp = urllib.request.urlopen(url_head)
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
locast2plex_1  |     return opener.open(url, data, timeout)
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
locast2plex_1  |     response = self._open(req, data)
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
locast2plex_1  |     result = self._call_chain(self.handle_open, protocol, protocol +
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
locast2plex_1  |     result = func(*args)
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 1379, in http_open
locast2plex_1  |     return self.do_open(http.client.HTTPConnection, req)
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 1354, in do_open
locast2plex_1  |     r = h.getresponse()
locast2plex_1  |   File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
locast2plex_1  |     response.begin()
locast2plex_1  |   File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
locast2plex_1  |     version, status, reason = self._read_status()
locast2plex_1  |   File "/usr/local/lib/python3.8/http/client.py", line 276, in _read_status
locast2plex_1  |     raise RemoteDisconnected("Remote end closed connection without"
locast2plex_1  | http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by wlfuer** [comment]
Well, I guess something got messed up with my docker ... I started looking into what to do and I used the reset config option, then re-setup locast2plex ... and it seems to be working like a champ. I'm going to blame an update to the system.

Surprised I didn't hit something like this before, I'll probably just reset things when I update.  

LOVE THIS SOLUTION! THANK YOU! -Bill
