### ISSUE TITLE
Could not communicate with device (Locast2Plex Docker - Plex Docker)

### ISSUE THREAD

**Issue by gewgaw4u** [tgorgdotcom/locast2plex#230]
I am running both dockers on a MACLAN so they have their own IPs Plex 192.168.0.222 and Locast2Plex 192.168.0.225. 

When I start Locast2Plex container all is well and initializes correctly. I require to manually enter the IP in the plex config and it finds it fine and show the 49 channels in New York. It wil ladd the line up no problem. However if I try to view a station or scan channels I receive a "Could not communicate with device"

Here is my config.ini

[main]
plex_accessible_ip = 192.168.0.225
locast_username = ME@DOMAIN.COM
locast_password = xxxxxx
uuid = jikyzolw

Here is my log from the Locast2Plex docker:

,Initiating Locast2Plex v0.6.5
,Opening and Verifying Configuration File.
,/app/config/config.ini
,/app/config.ini
,Loading Configuration File: /app/config.ini
,Tuner count set to 3
,Server is set to run on  192.168.0.225:6077
,UUID set to: jikyzolw...
,Getting user location...
,Getting location via IP Address.
,Got external IP 217.138.208.109.
,Got location as New York - DMA 501 - Lat\Lon 40.7185\-74.0025
,Logging into Locast using username ME@DOMAIN.COM...
,Validating User Info...
,User Info obtained.
,User didDonate: True
,User donationExpire: 2021-04-01 18:28:49
,Starting First time Stations refresh...
,Checking FCC facilities database for updates.
,Cached facilities database is current.
,Getting list of stations based on DMA...
,Found 49 stations for DMA 501
,Starting Stations thread...
,Starting device server on 192.168.0.225:6077
,Now listening for requests.
,Starting SSDP server...
,Starting First time EPG refresh...
,Registering upnp:rootdevice (http://192.168.0.225:6077/device.xml)
,FROM CACHE: /app/cache/501_epg/03-03-2021.json
,FROM CACHE: /app/cache/501_epg/03-04-2021.json
,FROM CACHE: /app/cache/501_epg/03-05-2021.json
,FROM CACHE: /app/cache/501_epg/03-06-2021.json
,FROM CACHE: /app/cache/501_epg/03-07-2021.json
,FROM CACHE: /app/cache/501_epg/03-08-2021.json
,Starting EPG thread...
,Locast2Plex is now online.
,192.168.0.222 - - [03/Mar/2021 06:17:25] "GET /discover.json HTTP/1.0" 200 -
,192.168.0.222 - - [03/Mar/2021 06:17:25] "GET /lineup_status.json HTTP/1.0" 200 -
,192.168.0.222 - - [03/Mar/2021 06:17:26] "GET /lineup.json HTTP/1.0" 200 -
,----------------------------------------
,Exception happened during processing of request from ('192.168.0.222', 34546)
,Traceback (most recent call last):
,  File "/usr/local/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
,    self.process_request(request, client_address)
,  File "/usr/local/lib/python3.8/socketserver.py", line 347, in process_request
,    self.finish_request(request, client_address)
,  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
,    self.RequestHandlerClass(request, client_address, self)
,  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
,    self.handle()
,  File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
,    self.handle_one_request()
,  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
,    method()
,  File "/app/lib/tuner_interface.py", line 222, in do_POST
,    self.do_response(200, 'text/html')
,TypeError: do_response() missing 1 required positional argument: 'reply_str'
,----------------------------------------

FYI.. the plex container is also on a bridged network in order to comminucate with a sonarr and radarr containers.

**Comment by gewgaw4u** [comment]
I have resolved my issue by doing to following:

-Was running my Glutun docker in MACLAN mode change to run in bridged mode using the same network as my plex container.
-Pulling version 0.5.3 of locast2plex code and docker version.
-setting my listen ip in config.ini to the internal IP (ie.. 172.20.0.xx)
-manual searching for the locast2plex instance using the 172.20.0.xx:6077 within plex.

All is well with no errors. 

Will attmept to deploy a new docker container with latest version and code. Will update here on results.

**Comment by gewgaw4u** [comment]
Created new docker with update code and docker versions and all works wodnerfully. It appears that error was related to not having the locast2plex, glutun and plex containers sitting on the same private bridge network (ie 172.20.0.xx).

RESOLVED
