### ISSUE TITLE
Issues running on Open Media Vault with Docker/Portainer

### ISSUE THREAD

**Issue by stormarcher3** [tgorgdotcom/locast2plex#234]
First, great work on the app. I have this working well on my Synology NAS. I'd love to run this on my raspberry pi, but need support for that architecture. 

I've setup a little x86 machine with the latest OMV and the extras. I have plex running now in a docker container and that is working well.  I'm having trouble deploying your app in this configuration. I had some issues getting the docker command to find the config.ini, but when I got that resolved I get a missing credentials error. Since this is the same file with a small edit (ip address), I'm a not sure what is causing it to not work. Here is the command and the error:

root@schomenas:/config/locast2plex# docker run -v /app/config.ini -p 6077:6077 -p 1900:1900/udp tgorg/locast2plex
Initiating Locast2Plex v0.6.5
Opening and Verifying Configuration File.
/app/config/config.ini
/app/config.ini
Loading Configuration File: /app/config.ini
Locast Login Credentials Missing. Exiting...

All files have full permissions. Next I tried running using python3 main.py. The application starts. I can connect with Plex and it builds the channel guide. When I try to tune a channel I get playback errors. here is the full log:

192.168.1.30 - - [09/Mar/2021 17:20:29] "GET /lineup.json HTTP/1.0" 200 -
Getting station info for 1091...
Determining best video stream for 1091...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
192.168.1.30 - - [09/Mar/2021 17:20:29] "GET /watch/1091 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.30', 33226)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/config/locast2plex/lib/tuner_interface.py", line 109, in do_GET
    self.do_tuning(contentPath.replace('/watch/', ''))
  File "/config/locast2plex/lib/tuner_interface.py", line 347, in do_tuning
    ffmpeg_proc = subprocess.Popen(ffmpeg_command, stdout=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'
----------------------------------------
Getting station info for 1091...
Determining best video stream for 1091...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
192.168.1.30 - - [09/Mar/2021 17:20:30] "GET /watch/1091 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.30', 33232)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/config/locast2plex/lib/tuner_interface.py", line 109, in do_GET
    self.do_tuning(contentPath.replace('/watch/', ''))
  File "/config/locast2plex/lib/tuner_interface.py", line 347, in do_tuning
    ffmpeg_proc = subprocess.Popen(ffmpeg_command, stdout=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'
----------------------------------------
Getting station info for 1091...
192.168.1.30 - - [09/Mar/2021 17:20:32] "GET /discover.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:32] "GET /lineup_status.json HTTP/1.0" 200 -
Determining best video stream for 1091...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
192.168.1.30 - - [09/Mar/2021 17:20:32] "GET /watch/1091 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.30', 33238)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/config/locast2plex/lib/tuner_interface.py", line 109, in do_GET
    self.do_tuning(contentPath.replace('/watch/', ''))
  File "/config/locast2plex/lib/tuner_interface.py", line 347, in do_tuning
    ffmpeg_proc = subprocess.Popen(ffmpeg_command, stdout=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'
----------------------------------------
192.168.1.30 - - [09/Mar/2021 17:20:35] "GET /discover.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:35] "GET /lineup_status.json HTTP/1.0" 200 -
Getting station info for 1091...
Determining best video stream for 1091...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
192.168.1.30 - - [09/Mar/2021 17:20:36] "GET /watch/1091 HTTP/1.1" 400 -
192.168.1.30 - - [09/Mar/2021 17:20:38] "GET /discover.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:38] "GET /lineup_status.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:41] "GET /discover.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:41] "GET /lineup_status.json HTTP/1.0" 200 -
Getting station info for 1091...
Determining best video stream for 1091...
192.168.1.30 - - [09/Mar/2021 17:20:44] "GET /discover.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:44] "GET /lineup_status.json HTTP/1.0" 200 -
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
192.168.1.30 - - [09/Mar/2021 17:20:44] "GET /watch/1091 HTTP/1.1" 400 -
192.168.1.30 - - [09/Mar/2021 17:20:47] "GET /discover.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:47] "GET /lineup_status.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:50] "GET /discover.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:50] "GET /lineup_status.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:53] "GET /discover.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:53] "GET /lineup_status.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:54] "GET /discover.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:20:54] "GET /lineup_status.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:21:10] "GET /discover.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:21:10] "GET /lineup.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:21:10] "GET /lineup_status.json HTTP/1.0" 200 -
Getting station info for 1117...
Determining best video stream for 1117...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
192.168.1.30 - - [09/Mar/2021 17:21:11] "GET /watch/1117 HTTP/1.1" 400 -
192.168.1.30 - - [09/Mar/2021 17:21:11] "GET /discover.json HTTP/1.0" 200 -
192.168.1.30 - - [09/Mar/2021 17:21:11] "GET /lineup_status.json HTTP/1.0" 200 -
^C^C received, shutting down the server
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/config/locast2plex/lib/ssdp_server.py", line 37, in ssdp_process
    ssdp.run(config["main"]["bind_ip"])
  File "/config/locast2plex/lib/ssdp_server.py", line 75, in run
    data, addr = self.sock.recvfrom(1024)
KeyboardInterrupt

The missing file/directory seems to be key, but not sure why.

Thanks!
Storm

**Comment by benmcmath** [comment]
I too would like to be able to run this on docker on my Pi4
