### ISSUE TITLE
Playback Error: Could not tune channel. Please check your tuner or antenna.

### ISSUE THREAD

**Issue by daburton263** [tgorgdotcom/locast2plex#237]
It worked last year but after updating Plex and Locast2plex it does not. Using command line. Plex allows setup of DVR with locast2plex. It loads the guide but whenever I try to watch I get error. Files are locast2plex.txt (stdout) and locast2plex.log (stderr).
[locast2plex.log](https://github.com/tgorgdotcom/locast2plex/files/6133118/locast2plex.log)
[locast2plex.txt](https://github.com/tgorgdotcom/locast2plex/files/6133120/locast2plex.txt)

**Comment by ccittadino-ctic** [comment]
I am noticing this too. Some time in the past few weeks. I've had to restart locat2plex on my Unraid server multiple times to get the tuner to work again. It works again for a day or so, then I start getting the error from the OP.

**Comment by sillydino** [comment]
I am noticing this too. Some time in the past few weeks. I've had to restart locat2plex on my Unraid server multiple times to get the tuner to work again. It works again for a day or so, then I start getting the error from the OP.

**Comment by RollingOnChrome** [comment]
I am having the same problem and had to restart my Docker VM in order to get Locast2Plex to work again.

**Comment by d3acon15** [comment]
Qq, how are you restarting the service. restarting the box or just kill the process and starting the service (just curious).

**Comment by aresrin** [comment]
Getting this same "Could not tune channel" error
Using:
Windows 10
Python 3.7
locast2plex 0.6.7 installed via terminal

Get this error message in the cmd window:
Exception happened during processing of request from ('192.168.1.131', 11659)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\locast2plex-main\lib\tuner_interface.py", line 126, in do_GET
    self.do_tuning(sid)
  File "C:\locast2plex-main\lib\tuner_interface.py", line 351, in do_tuning
    ffmpeg_proc = subprocess.Popen(ffmpeg_command, stdout=subprocess.PIPE)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable

**Comment by aresrin** [comment]
> Getting this same "Could not tune channel" error
> Using:
> Windows 10
> Python 3.7
> locast2plex 0.6.7 installed via terminal

UPDATE
I got it to work by uninstalling Python 3.7 and then installing Python 3.9.6 with Chocolaty in the admin powershell.
