### ISSUE TITLE
Unable to update Config file.

### ISSUE THREAD

**Issue by embywatcher** [tgorgdotcom/locast2plex#262]
I apologize if this issue was already identified; however, I wasn't able to location any information on the following.

When I try to install the latest release tvheadend-locast-0.8.6b.exe on my Windows 10 emby server, I get the following error during installation:

_"Unable to update Config file. Edit the file manually. 1 Traceback (most recent call last):
 File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
  return _run_code(code, main_globals, None,
 File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
  exec(code,m run_globals)
 File "C:\Program Files\tvheadend-locast\build\WINDOWS\UpdateConfig.pyw", line 81, in
  <module>
   configObj = get_config(install_dir, opersystem, args)
 File "C:\Program Files\tvheadend-locast\lib\config\user_config.py", line
  36, in get_config
   return TVHUserConfig(script_dir, opersystem, args)
 File "C:\Program Files\tvheadend-locast\lib\config\user_config.py", line
  58, in __init__
   self.defn_json = config_defn.load_default_config_defns()
 File "C:\Program Files\tvheadend-locast\lib\config\config_defn.py", line
  40, in load_default_config_defns
   defn_obj.merge_defn_file(CONFIG_DEFN_PATH, defn_file)
 File "C:\Program FIles\tvheadend-locast\lib\config\]config_defn.py", I  "_

The error seems like it continues, but isnt' displayed in the dialog box.  All I can do is click "OK".

The installation continues until its completed.  However, I am unable to start the tvheadend-locast services.

I receive the following when I attempt to start the service

_"Windows could not start the TVHeadend-Locast service on Local Computer. The service did not return an error. 
This could be an internal Windows error or an internal service error.
If the problem persists, contact your system administrator."_

Thank you for any guidance and assistance on this issue.

**Comment by rocky4546** [comment]
I would recommend you add an issue to the correct app.  Please go to 
https://github.com/rocky4546/tvheadend-locast/issues
and add a issue there.  Although I believe it is something that has been found and resolved in 0.8.4d

**Comment by embywatcher** [comment]
Thank you.  You are correct that this problem isn't occurring with the latest release (8.6.d).  I will post any further issues in the correct app.
