### ISSUE TITLE
network binding issue

### ISSUE THREAD

**Issue by null-character** [tgorgdotcom/locast2plex#264]
> Starting Stations thread...
> Starting device server on 10.0.0.200:6077
> Traceback (most recent call last):
>   File "main.py", line 75, in <module>
>     tuner_interface.start(config, locast, location_info.location)
>   File "/home/locast/share/locast2plex/lib/tuner_interface.py", line 439, in start
>     serverSocket.bind((config["main"]['bind_ip'], int(config["main"]['bind_port'])))
> OSError: [Errno 99] Cannot assign requested address

Hello I get the following error when trying to run the script in Debian Linux. Anyone have any ideas?

I am trying to run this in Linux because it starts in Windows but no streams actually work.

**Comment by null-character** [comment]
I figured it out. I had the wrong ip in the config file like a dope.
