### ISSUE TITLE
Service Runs, Plex can't start a stream

### ISSUE THREAD

**Issue by Deakon80** [tgorgdotcom/locast2plex#39]
This is running on a file server with nothing else running.  Plex was able to see everything and it was setup without issue, but it can't start a stream.

Output:

192.168.1.149 - - [19/Aug/2020 14:55:17] "GET /discover.json HTTP/1.0" 200 -
192.168.1.149 - - [19/Aug/2020 14:55:17] "GET /lineup_status.json HTTP/1.0" 200 -
Getting station info for 752...
Determining best video stream for 752...
Found 4 Playlists
752 will use 1280x720 resolution at 2700000bps
192.168.1.149 - - [19/Aug/2020 14:55:19] "GET /watch/752 HTTP/1.1" 200 -

Exception happened during processing of request from ('192.168.1.149', 64888)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "C:\Python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "C:\Locast2Plex\main.py", line 95, in do_GET
    ffmpeg_proc = subprocess.Popen(["ffmpeg", "-i", channelUri, "-codec", "copy", "-f", "mpegts", "pipe:1"], stdout=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by vipthomps** [comment]
Do you have ffmpeg installed on Windows (and is the PATH variable working? by that can you open a command prompt and just type ffmpeg?)

**Comment by Deakon80** [comment]
Yup, that was it, thank you, works perfectly now.
