### ISSUE TITLE
Locast Validation Error

### ISSUE THREAD

**Issue by java007md** [tgorgdotcom/locast2plex#40]
Running on linux via command line. Was able to start up the program fine yesterday (after hardcoding the latitude and longitude due to a geo code problem). The connection to both Plex and Jellyfin was working great last night, but the program will not successfully start up today.

Error message generated is bellow:

`Traceback (most recent call last):
  File "main.py", line 320, in <module>
    if (not locast.login(CONFIG_LOCAST_USERNAME, CONFIG_LOCAST_PASSWORD)) or (not locast.validate_user()):
  File "/root/locast2plex/LocastService.py", line 50, in login
    print("Error during login: " + loginErr.message)
TypeError: cannot concatenate 'str' and 'getset_descriptor' objects
`
Will dig into this a little more, but I'm not sure what changed to cause the failure today.

**Comment by java007md** [comment]
User error. VPN was started by another user and that was the source of the error.
