### ISSUE TITLE
KeyError: '553'

### ISSUE THREAD

**Issue by deathbybandaid** [tgorgdotcom/locast2plex#54]
I already knew that Locast wasn't available in my area, but I was bored and wanted to see what locast2plex would do.
Essentially, $5 found a bug, that should exit more cleanly.

````
root@locast2plex:/home/locast2plex# python main.py -u:REDACTED -p:REDACTED --debug --addy:0.0.0.0
Locast2Plex v0.4.2
DEBUG MODE ACTIVE
UUID found.
UUID set to: REDACTED...
Logging into Locast using username REDACTED...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1601232517
Getting user location...
User location obtained as REDACTED
Getting user's media market (DMA)...
DMA found as 553
Getting list of stations based on DMA...
Loading FCC Stations list...
Traceback (most recent call last):
  File "main.py", line 335, in <module>
    station_list = locast.get_stations()
  File "/home/locast2plex/LocastService.py", line 195, in get_stations
    fcc_market = dma_mapping[str(self.current_dma)]
KeyError: '553'
````

**Comment by deathbybandaid** [comment]
Closing as the issue doesn't happen since newer releases
