### ISSUE TITLE
KeyError: '678'

### ISSUE THREAD

**Issue by xirian** [tgorgdotcom/locast2plex#59]
When I try to start the docker it does this:

Locast2Plex v0.4.2
Traceback (most recent call last):
  File "/app/main.py", line 335, in <module>
DEBUG MODE ACTIVE
UUID found.
UUID set to: jkqzvwui...
Logging into Locast using username chris@chrisw.us...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1603285396
Getting user location...
User location obtained as 37.751/-97.822
Getting user's media market (DMA)...
DMA found as 678
Getting list of stations based on DMA...
Loading FCC Stations list...
    station_list = locast.get_stations()
  File "/app/LocastService.py", line 195, in get_stations
    fcc_market = dma_mapping[str(self.current_dma)]
KeyError: '678'

From what I can tell it thinks my DMA is in kansas but I'm in New York and can stream locast fine in the tv apps.

**Comment by tgorgdotcom** [comment]
Are you running a VPN by any chance?  That might affect location.  Otherwise check here for information on getting your location correct: https://github.com/tgorgdotcom/locast2plex/issues/22#issuecomment-686237578

**Comment by deathbybandaid** [comment]
{'city': 'New York', 'dma_code': 501, 'latitude': 40.714269100000003, 'longitude': -74.005972900000003, 'region': 'NY', 'slug': 'new-york-ny'}

**Comment by tgorgdotcom** [comment]
Hello @xirian.  Are you still running into issues?
