### ISSUE TITLE
Could not tune channel. Please check your tuner or antenna.

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [tgorgdotcom/locast2plex#88]
```
Exception happened during processing of request from ('XXX.XXX.XXX.XXX', 36650)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 639, in __init__
    self.handle()
  File "C:\Python27\lib\BaseHTTPServer.py", line 337, in handle
    self.handle_one_request()
  File "C:\Python27\lib\BaseHTTPServer.py", line 325, in handle_one_request
    method()
  File "C:\locast2plex\main.py", line 95, in do_GET
    channelUri = self.local_locast.get_station_stream_uri(channelId)
  File "C:\locast2plex\LocastService.py", line 469, in get_station_stream_uri
    videoUrlM3u = m3u8.load(videoUrlRes['streamUrl'])
  File "C:\locast2plex\m3u8\__init__.py", line 56, in load
    return _load_from_uri(uri, timeout, headers, custom_tags_parser, verify_ssl)
  File "C:\locast2plex\m3u8\__init__.py", line 68, in _load_from_uri
    resource = urlopen(request, timeout=timeout, context=context)
TypeError: urlopen() got an unexpected keyword argument 'context'
```

**Comment by FozzieBear** [comment]
What version of Python 2.7 are you running? The `context` parameter wasn't added until 2.7.9, so if you'll likely need to upgrade to a later release if you're on a release earlier than that.

**Comment by Cookie-Monster-Coder** [comment]
> 
> 
> What version of Python 2.7 are you running? The `context` parameter wasn't added until 2.7.9, so you'll likely need to upgrade to a later release if you're on a release earlier than that.

Thank you! That worked!
